name: Post new Starting Hand
run-name: Post new Starting Hand
on: [workflow_dispatch, push]
jobs:
  post-new-starting-hand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run script
        env:
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: ./script.sh