name: Post new Starting Hand
run-name: Post new Starting Hand
on:
  workflow_dispatch:
    inputs:
      subreddit:
        description: 'The subreddit to post to'
        required: true
        default: 'test'
        type: string
      message:
        description: 'Intro message before the post'
        required: false
        default: ''
        type: string
jobs:
  post-new-starting-hand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true
      - run: bundle install
      - name: Generate post
        run: bundle exec ruby generate_text.rb
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          INTRO_MESSAGE: ${{ inputs.message }}
      - name: Post to reddit
        env:
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          SUBREDDIT: ${{ inputs.subreddit }}
        run: ./post_to_reddit.sh