name: Post new Starting Hand
run-name: Post new Starting Hand
on:
  workflow_dispatch:
    inputs:
      subreddit:
        description: 'The subreddit to post to'
        required: true
        default: 'test'
        type: string
jobs:
  post-new-starting-hand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate post
        run: ./run.rb > post.md
      - name: Upload post text
        uses: actions/upload-artifact@v4
        with:
          name: post-md
          path: post.md
      # - name: run script
      #   env:
      #     REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      #     REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #     SUBREDDIT: ${{ inputs.subreddit }}
      #   run: ./script.sh