name: Test script
run-name: ${{ github.actor }} is testing script
on: [workflow_dispatch, push]
jobs:
  test-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run script
        env:
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: ./script.sh